name: CI

on:
  push:
    branches: 
      - master
    paths-ignore:
      - .env.sample
      - .gitignore
      - config.json.sample
      - LICENSE
      - README.md
      - .github/**
      - .vscode/**
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: |
          python -m pip install poetry==1.4.2
      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: |
          python -m poetry install
      - name: Run tests
        run: |
          poetry run python3 $(git ls-files '*.py')

  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: |
          python -m pip install poetry==1.4.2
      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: |
          python -m poetry install
      - name: Lint with Pylint
        run: |
          poetry run pylint $(git ls-files '*.py')

  success-all-test:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - lint
      - build
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - name: Check failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1
      
      - name: Success
        run: echo "All done"
        if: ${{ success() }}
